import "./globals.css";
import type { Metadata } from "next";
import { lato } from "@/lib/font";
import Header from "@/components/organisms/Header/Main";
import MainLayout from "@/components/templates/MainLayout";
import StairTransition from "@/components/molecules/StairTransition";

export const metadata: Metadata = {
	title: "Franz Monzales - Website Portfoilo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${lato.className} antialiased`}>
				<Header />
				<StairTransition />
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
